export const productos = [{
    id: 1,
    nombre: "Star Wars: Jedi Fallen Order",
    precio: 1500,
    genero: 'aventura',
    desarrolladores: "Respawn Entertainment",
    img: "../assets/fallen-order.webp",
    stock: 5,
    comprado: true,
    carrusel_1: "../assets/fallen-order-1.jpg",
    carrusel_2: "../assets/fallen-order-2.webp",
    carrusel_3: "../assets/fallen-order-3.jpg"
  },
  {
    id: 2,
    nombre: "Elden Ring",
    precio: 2200,
    genero: 'accion',
    desarrolladores: "FromSoftware",
    img: "../assets/elden-ring.webp",
    stock: 2,
    comprado: false,
    carrusel_1: "../assets/elden-ring-1.jpg",
    carrusel_2: "../assets/elden-ring-2.jpg",
    carrusel_3: "../assets/elden-ring-3.jpg"
  },
  {
    id: 3,
    nombre: "God of War",
    precio: 4400,
    genero: "accion",
    desarrolladores: "SCE Santa Monica Studio",
    img: "../assets/god-of-war.jfif",
    stock: 7,
    comprado: false,
    carrusel_1: "../assets/god-of-war-1.jpg",
    carrusel_2: "../assets/god-of-war-2.jpg",
    carrusel_3: "../assets/god-of-war-3.jfif"
  },
  {
    id: 4,
    nombre: "Multiversus",
    precio: 0,
    genero: 'pelea',
    desarrolladores: "Player First Games",
    img: "../assets/multiversus.jpg",
    stock: 12,
    comprado: true,
    carrusel_1: "../assets/multiversus-1.webp",
    carrusel_2: "../assets/multiversus-2.webp",
    carrusel_3: "../assets/multiversus-3.jfif"
  },
  {
    id: 5,
    nombre: "Horizon Zero Dawn",
    precio: 3800,
    genero: 'aventura',
    desarrolladores: "Guerrilla Games",
    img: "../assets/horizon.webp",
    stock: 5,
    comprado: false,
    carrusel_1: "../assets/horizon-1.webp",
    carrusel_2: "../assets/horizon-2.jfif",
    carrusel_3: "../assets/horizon-3.jpg"
  },
  {
    id: 6,
    nombre: "Hogwarts: Legacy",
    precio: 6000,
    genero: 'rol',
    desarrolladores: "Avalanche Software",
    img: "../assets/hogwarts.jfif",
    stock: 0,
    comprado: false,
    carrusel_1: "../assets/hogwarts-1.jpg",
    carrusel_2: "../assets/hogwarts-2.jpg",
    carrusel_3: "../assets/hogwarts-3.jpg"
  }]